name: mcquenji_core
description: "A new Flutter package project."
version: 1.1.0
homepage: "Core module for all my flutter apps."

environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter_bloc: ^8.1.4
  dio: ^5.4.3+1
  either_dart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_modular: ^6.3.3
  freezed_annotation: ^2.4.1
  logging: ^1.2.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2

flutter: null
